GET http://127.0.0.1:10001/movies/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVtYWlsQGVtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTY5MzU3Nzc3N30.mckCoVocHgyreT8hxP2T0MsGn7VL5lojWUyWtGzERz8
###

GET http://127.0.0.1:10001/movies/?status=new
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZhc3lhQHNreXByby5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE2Nzc5MTU2NDN9.-TYavzDCAucIvNY8Y0wUU4J7Qey56fQQfYrtN3bNGek

###
GET http://127.0.0.1:10001/movies/?status=new&page=2
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZhc3lhQHNreXByby5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE2Nzc5MTU2NDN9.-TYavzDCAucIvNY8Y0wUU4J7Qey56fQQfYrtN3bNGek

###
GET http://127.0.0.1:10001/movies/?page=2
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZhc3lhQHNreXByby5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE2Nzc5MTU2NDN9.-TYavzDCAucIvNY8Y0wUU4J7Qey56fQQfYrtN3bNGek

###

GET http://127.0.0.1:10001/directors/?page=1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZhc3lhQHNreXByby5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE2Nzc5MTU2NDN9.-TYavzDCAucIvNY8Y0wUU4J7Qey56fQQfYrtN3bNGek
###


GET http://127.0.0.1:10001/directors/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZhc3lhQHNreXByby5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE2Nzc5MTU2NDN9.-TYavzDCAucIvNY8Y0wUU4J7Qey56fQQfYrtN3bNGek


###

GET http://127.0.0.1:10001/directors/1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZhc3lhQHNreXByby5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE2Nzc5MTU2NDN9.-TYavzDCAucIvNY8Y0wUU4J7Qey56fQQfYrtN3bNGek

###

GET http://127.0.0.1:10001/genres/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZhc3lhQHNreXByby5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE2Nzc5MTU2NDN9.-TYavzDCAucIvNY8Y0wUU4J7Qey56fQQfYrtN3bNGek

###
GET http://127.0.0.1:10001/users/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZhc3lhQHNreXByby5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE2NzgwMDU2OTN9.FaJf_Y9ZWrrR5qcc9xXV0xoeDkApkDE1kFc_NQwQ_B0

###

GET http://127.0.0.1:10001/genres/?page=1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZhc3lhQHNreXByby5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE2Nzc5MTU2NDN9.-TYavzDCAucIvNY8Y0wUU4J7Qey56fQQfYrtN3bNGek
###

GET http://127.0.0.1:10001/genres/2
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZhc3lhQHNreXByby5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE2Nzc5MTU2NDN9.-TYavzDCAucIvNY8Y0wUU4J7Qey56fQQfYrtN3bNGek

###

GET http://127.0.0.1:10001/movies/20
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZhc3lhQHNreXByby5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE2Nzc5MTU2NDN9.-TYavzDCAucIvNY8Y0wUU4J7Qey56fQQfYrtN3bNGek

###

POST http://127.0.0.1:10001/movies/
Accept: application/json
Content-Type: application/json

{
  "title": "Гарри Поттер мой кумир!",
  "trailer": "таким фильмам не нужны трейлеры",
  "year": 1990,
  "rating": 10,
  "description": "10 из 10!"
}

###

PUT http://127.0.0.1:10001/movies/21
Accept: application/json
Content-Type: application/json

{
  "id": 21,
  "title": "-------",
  "trailer": "-----",
  "year": 0,
  "rating": 0,
  "description": "0 из 10!",
  "genre_id": 1,
  "director_id": 1
}

###

PATCH http://127.0.0.1:10001/movies/3
Accept: application/json
Content-Type: application/json

{
  "id": 21,
  "title": "-------",
  "trailer": "-----",
  "year": 0,
  "rating": 0,
  "description": "0 из 10!",
  "genre_id": 1,
  "director_id": 1
}

###

DELETE http://127.0.0.1:10001/users/

###

GET http://127.0.0.1:10001/users/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZhc3lhQHNreXByby5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE2Nzc4NjIxODJ9.ZM6lrU9fPqNHtZm7Y19k9P7J3WuyT9ik_rOyfQEzLwo
